# run in container
sudo: false

# install dependencies
# addons:
#  apt:
#    packages:
#    - libboost-all-dev
  

# we compile a c++ project
language: cpp

# test with gcc and clang
compiler:
  - gcc
#  - clang

# prepare compilation  
before_script:
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub install ugcore LuaShell
  - mkdir build && cd build && cmake ../ -DTARGET=ugshell -DLAPACK=OFF -DBLAS=OFF -DDIM="1;2;3" -DCOMPILE_INFO=OFF

# compile ug
script: travis_wait 640 make 
